model: 'ParTevent_Xbb_Hl'
subset_batches: 0.3  
lr: 0.001
bs: 256
ep: 30
nlayer-mlp: 3
nodes-mlp: 128
njets-mlp: 5
config: '../../Finetune_hep/config/myJetClass_full.yaml'
ParT-weights: 'no'
mlp-weights: 'no'
data: '/raven/u/mvigl/Finetune_hep_dir/config/train_list.txt'
data-val: '/raven/u/mvigl/Finetune_hep_dir/config/val_list.txt'
Xbb: 'no'
Xbb-val: 'no' 
Ntrainings: 1
alpha: 0
project-name: 'Finetuning_hep'
default: False
subset: True
api-key: 'r1SBLyPzovxoWBPDLx3TAE02O'
ws: 'mvigl'
checkpoint: '/raven/u/mvigl/Finetune_hep_dir/run/ParTevent_Xbb_Hl_scratch_subset_4/models/ParTevent_Xbb_Hl_hl3_nodes128_nj5_lr0.001_bs256_training_1subset_2940006.pt'
check-message: 'no'
start-epoch: 0
Fyaml: '/raven/u/mvigl/Finetune_hep_dir/run/ParTevent_subset/config/train_ParTevent_1.yaml'
