modeltype: 'ParTevent_Xbb_Hl_double'
Ntraining: 4
filelist-test: '/raven/u/mvigl/Finetune_hep_dir/config/test_list.txt'
config-path: '../../Finetune_hep/config/myJetClass_full.yaml'
Xbb-scores-path: 'no'
model-path: '/raven/u/mvigl/Finetune_hep_dir/run/ParTevent_Xbb_Hl_full_double/models/ParTevent_Xbb_Hl_hl3_nodes128_nj5_lr0.001_bs256_WparT_Wmlp_training_4_epoch_3_Val_loss_0.09532013535499573.pt'