
inputs:
   pf_points:
      length: 110
      pad_mode: wrap
      vars: 
         - [pfcand_deta, null]
         - [pfcand_dphi, null]
   pf_features:
      length: 110
      pad_mode: wrap
      vars: 
      ### [format 1]: var_name (no transformation)
      ### [format 2]: [var_name, 
      ###              subtract_by(optional, default=None, no transf. if preprocess.method=manual, auto transf. if preprocess.method=auto), 
      ###              multiply_by(optional, default=1), 
      ###              clip_min(optional, default=-5), 
      ###              clip_max(optional, default=5), 
      ###              pad_value(optional, default=0)]
         - ['pfcand_pt_log', null]
         - ['pfcand_e_log', null]
         - ['pfcand_logptrel', null]
         - ['pfcand_logerel', null]
         - ['pfcand_deltaR', null]
         - ['pfcand_charge', null]
         - ['pfcand_isChargedHad', null]
         - ['pfcand_isNeutralHad', null]
         - ['pfcand_isGamma', null]
         - ['pfcand_isEl', null]
         - ['pfcand_isMu', null]
         - ['pfcand_dz', null]
         - ['pfcand_dzerr', null]
         - ['pfcand_dz', null]
         - ['pfcand_dzerr', null]
         - ['pfcand_deta', null]
         - ['pfcand_dphi', null]
   pf_vectors:
      length: 110
      pad_mode: wrap
      vars: 
         - [pfcand_px, null]
         - [pfcand_py, null]
         - [pfcand_pz, null]
         - [pfcand_energy, null]
   pf_mask:
      length: 110
      pad_mode: constant
      vars: 
         - [pfcand_mask, null]

labels:
   ### type can be `simple`, `custom`
   ### [option 1] use `simple` for binary/multi-class classification, then `value` is a list of 0-1 labels
   type: simple
   #value: [label_QCD, label_Hbb, label_Hcc, label_Hgg, label_H4q, label_Hqql, label_Zqq, label_Wqq, label_Tbqq, label_Tbl]
   value: ['label_H_bb']




