model: 'baseline'
lr: 0.001
bs: 512
ep: 30
nlayer-mlp: 3
nodes-mlp: 24
njets-mlp: 5
config: '../../Finetune_hep/config/myJetClass_full.yaml'
ParT-weights: 'no'
mlp-weights: 'no'
data: '/home/iwsatlas1/mavigl/Finetune_hep_dir/Finetune_hep/config/train_list.txt'
data-val: '/home/iwsatlas1/mavigl/Finetune_hep_dir/Finetune_hep/config/val_list.txt'
Xbb: 'no'
Xbb-val: 'no' 
Ntrainings: 1
alpha: 0
project-name: 'Finetune_hep'
default: False
subset: True
api-key: 'r1SBLyPzovxoWBPDLx3TAE02O'
ws: 'mvigl'
