model: 'mlpXbb'
lr: 0.001
bs: 512
ep: 30
nlayer-mlp: 3
nodes-mlp: 12
njets-mlp: 5
config: 'no'
ParT-weights: 'no'
mlp-weights: 'no'
data: '/raven/u/mvigl/Finetune_hep_dir/config/train_list.txt'
data-val: '/raven/u/mvigl/Finetune_hep_dir/config/val_list.txt'
Xbb: '/raven/u/mvigl/Finetune_hep_dir/Finetune_hep/models/ParTXbb/train_ParTXbb_score_training_1.h5' 
Xbb-val: '/raven/u/mvigl/Finetune_hep_dir/Finetune_hep/models/ParTXbb/val_ParTXbb_score_training_1.h5'
Ntrainings: 1
alpha: 0
project-name: 'Finetuning_hep'
default: False
subset: False
api-key: 'r1SBLyPzovxoWBPDLx3TAE02O'
ws: 'mvigl'
checkpoint: 'no'
check-message: 'no'
start-epoch: 0
Fyaml: '/home/iwsatlas1/mavigl/Finetune_hep_dir/Finetune_hep/config/train_ParTHlXbb.yaml'