model: 'ParTXbb'
lr: 0.001
bs: 512
ep: 1
nlayer-mlp: 0
nodes-mlp: 128
njets-mlp: 1
config: '../../Finetune_hep/config/myJetClass_full.yaml'
ParT-weights: '../../Finetune_hep/models/ParT_full.pt'
mlp-weights: 'no'
data: '/home/iwsatlas1/mavigl/Finetune_hep_dir/Finetune_hep/config/train_list.txt'
data-val: '/home/iwsatlas1/mavigl/Finetune_hep_dir/Finetune_hep/config/val_list.txt'
Xbb: 'no' 
Xbb-val: 'no' 
Ntrainings: 1
alpha: 0
project-name: 'Finetune_hep'
default: False
subset: True
api-key: 'r1SBLyPzovxoWBPDLx3TAE02O'
ws: 'mvigl'
checkpoint: 'no'
check-message: 'no'
start-epoch: 0
Fyaml: '/home/iwsatlas1/mavigl/Finetune_hep_dir/Finetune_hep/config/train_ParTXbb.yaml'