modeltype: 'ParTevent'
Ntraining: 4
filelist-test: '/raven/u/mvigl/Finetune_hep_dir/config/test_list.txt'
config-path: '../../Finetune_hep/config/myJetClass_full.yaml'
Xbb-scores-path: 'no'
model-path: '/raven/u/mvigl/Finetune_hep_dir/run/ParTevent/models/ParTevent_hl3_nodes128_nj5_lr0.001_bs256_WparT_training_4_epoch_4_Val_loss_0.0982135757803917.pt'