model: 'ParTevent_Xbb_Hl'
lr: 0.001
bs: 256
ep: 10
nlayer-mlp: 3
nodes-mlp: 128
njets-mlp: 5
config: '../../Finetune_hep/config/myJetClass_full.yaml'
ParT-weights: '/raven/u/mvigl/Finetune_hep_dir/run/ParTXbb_scratch/models/ParTXbb_hl0_nodes128_nj1_lr0.001_bs512_training_2_epoch_10_Val_loss_0.1555159091949463.pt'
mlp-weights: '/raven/u/mvigl/Finetune_hep_dir/run/mlpHlXbb/models/mlpHlXbb_hl4_nodes24_nj5_lr0.001_bs512_training_2.pt'
data: '/raven/u/mvigl/Finetune_hep_dir/config/train_list.txt'
data-val: '/raven/u/mvigl/Finetune_hep_dir/config/val_list.txt'
Xbb: 'no'
Xbb-val: 'no'
Ntrainings: 2
alpha: 0
project-name: 'Finetuning_hep'
default: False
subset: False
api-key: 'r1SBLyPzovxoWBPDLx3TAE02O'
ws: 'mvigl'
checkpoint: 'no'
check-message: 'no'
start-epoch: 0
Fyaml: '/raven/u/mvigl/Finetune_hep_dir/run/ParTevent_Xbb_Hl/config/train_ParTevent_2.yaml'
